from pathlib import Path
from typing import Any

from mflux.utils.version_util import VersionUtil


class ModelCardSaver:
    CONTRIBUTOR = "[@lpalbou](https://huggingface.co/lpalbou)"
    DEFAULT_NAMESPACE = "AbstractFramework"
    PROJECT_URL = "https://github.com/lpalbou/mlx-gen"
    QUANTIZATION_DOC_URL = "https://github.com/lpalbou/mlx-gen/blob/main/docs/quantization.md"
    FLUX_NON_COMMERCIAL_LICENSE_NAME = "flux-non-commercial-license"
    FLUX_NON_COMMERCIAL_LICENSE_DISPLAY_NAME = "FLUX Non-Commercial License"
    FLUX_NON_COMMERCIAL_LICENSE_LINK = (
        "https://huggingface.co/black-forest-labs/FLUX.2-klein-9B/blob/main/LICENSE.md"
    )
    FLUX_ACCEPTABLE_USE_POLICY_LINK = "https://bfl.ai/legal/usage-policy"

    @staticmethod
    def save_model_card(base_path: str, model: Any, bits: int | None) -> None:
        path = Path(base_path)
        path.mkdir(parents=True, exist_ok=True)
        (path / "README.md").write_text(
            ModelCardSaver.render_model_card(
                base_path=base_path,
                model=model,
                bits=bits,
            ),
            encoding="utf-8",
        )

    @staticmethod
    def render_model_card(base_path: str, model: Any, bits: int | None) -> str:
        model_name = ModelCardSaver._model_name(model)
        terms = ModelCardSaver._model_terms(model)
        repo_name = Path(base_path).name or ModelCardSaver._repo_name(model_name)
        repo_id = f"{ModelCardSaver.DEFAULT_NAMESPACE}/{repo_name}"
        pipeline_tag = ModelCardSaver._pipeline_tag(terms)
        tags = ModelCardSaver._tags(terms, bits, pipeline_tag)
        frontmatter = ModelCardSaver._frontmatter(model_name, terms, pipeline_tag, tags)

        sections = [
            frontmatter,
            f"# {repo_name}",
            "",
            (
                f"This repository contains MLX-Gen saved weights for `{model_name}`. "
                "The checkpoint is designed for local Apple Silicon inference with "
                f"[`mlx-gen`]({ModelCardSaver.PROJECT_URL})."
            ),
            "",
            "It uses the mflux/MLX saved-weight layout and MLX quantization tensors. "
            "It is not a Diffusers or Transformers `from_pretrained()` checkpoint.",
            "",
            "## Source Model",
            "",
            ModelCardSaver._source_model_line(model_name),
            "",
            *ModelCardSaver._license_section(model_name, terms),
            "",
            "## Quantization",
            "",
            ModelCardSaver._quantization_section(terms, bits),
            "",
            "## Compatibility",
            "",
            f"Requires `mlx-gen >= {VersionUtil.get_mflux_version()}`.",
            "",
            f"Generated with `mlx-gen {VersionUtil.get_mflux_version()}`.",
            "",
            "Use the `mlxgen` command and Python import path for new MLX-Gen projects.",
            "",
            "## Usage",
            "",
            "```bash",
            "python -m pip install -U mlx-gen",
            "",
            f"mlxgen download --model {repo_id}",
            "",
            "mlxgen generate \\",
            f"  --model {repo_id} \\",
            *ModelCardSaver._usage_lines(pipeline_tag, terms),
            "```",
            "",
            "## Attribution",
            "",
            "MLX-Gen is based on [mflux](https://github.com/filipstrand/mflux) by "
            "Filip Strand and the original mflux contributors. This model card is "
            "generated by MLX-Gen so derived checkpoints keep that attribution visible.",
            "",
            ModelCardSaver._contributor_line(bits),
            "",
        ]
        return "\n".join(sections)

    @staticmethod
    def _frontmatter(model_name: str, terms: str, pipeline_tag: str, tags: list[str]) -> str:
        lines = [
            "---",
        ]
        lines.extend(ModelCardSaver._license_frontmatter(model_name, terms))
        lines.extend(
            [
                f"base_model: {model_name}",
                f"pipeline_tag: {pipeline_tag}",
                "library_name: mlx-gen",
                "tags:",
            ]
        )
        lines.extend([f"- {tag}" for tag in tags])
        lines.append("---")
        return "\n".join(lines)

    @staticmethod
    def _license_frontmatter(model_name: str, terms: str) -> list[str]:
        if ModelCardSaver._is_flux2_9b(model_name, terms):
            return [
                "license: other",
                f"license_name: {ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_NAME}",
                f"license_link: {ModelCardSaver._flux_noncommercial_license_link(model_name)}",
                (
                    "extra_gated_prompt: \"Access is for non-commercial use under the "
                    "FLUX Non-Commercial License and Black Forest Labs Acceptable Use Policy. "
                    "This repository is a quantized derivative of a gated Black Forest Labs "
                    "FLUX.2 Klein 9B model.\""
                ),
                "extra_gated_fields:",
                "  I agree to use this model for non-commercial use only: checkbox",
                "  I agree to follow the FLUX Non-Commercial License: checkbox",
                "  I acknowledge the Black Forest Labs Acceptable Use Policy: checkbox",
            ]

        if ModelCardSaver._is_apache_model(model_name, terms):
            return ["license: apache-2.0"]

        return []

    @staticmethod
    def _license_section(model_name: str, terms: str) -> list[str]:
        if ModelCardSaver._is_flux2_9b(model_name, terms):
            return [
                "## License and Access",
                "",
                (
                    "This checkpoint is a quantized derivative of a gated "
                    "Black Forest Labs FLUX.2 Klein 9B source model. The source model is "
                    f"distributed under the [{ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_DISPLAY_NAME}]"
                    f"({ModelCardSaver._flux_noncommercial_license_link(model_name)})."
                ),
                "",
                (
                    "Host this derivative as a gated Hugging Face repository and require users "
                    "to accept the same non-commercial license terms and "
                    f"[Black Forest Labs Acceptable Use Policy]({ModelCardSaver.FLUX_ACCEPTABLE_USE_POLICY_LINK}) "
                    "before accessing the files."
                ),
            ]

        if ModelCardSaver._is_apache_model(model_name, terms):
            return [
                "## License and Access",
                "",
                "This quantized derivative follows the Apache 2.0 license of the source model.",
            ]

        return []

    @staticmethod
    def _quantization_section(terms: str, bits: int | None) -> str:
        if bits == 4 and "qwen" in terms:
            return "\n".join(
                [
                    "This is a mixed q4/q8 checkpoint for Qwen Image generation and editing. "
                    "Fully q4 Qwen checkpoints can lose coherent generative behavior, so MLX-Gen "
                    "uses a mixed policy:",
                    "",
                    "- q4 for most Qwen transformer attention, feed-forward, and projection linears.",
                    "- q8 for Qwen `*.img_mod_linear` transformer modulation layers.",
                    "- q4 for group64-compatible Qwen text-encoder language linears.",
                    "- q8 for group64-compatible Qwen text-encoder visual linears.",
                    "- BF16 for the VAE, norms, embeddings, and linears that are not MLX group64-compatible.",
                    "",
                    f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                    "for the current mixed q4/q8 policy and compatibility notes.",
                ]
            )

        if bits == 8:
            section = (
                "This is an MLX q8 checkpoint. Quantizable modules are saved at 8-bit where "
                "the model layout supports MLX quantization; VAE weights and non-quantizable "
                "layers remain BF16."
            )
            if "qwen" in terms:
                section += (
                    " The Qwen-specific mixed q4/q8 policy only applies when preparing Qwen models "
                    f"with `--quantize 4`; see the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL})."
                )
            return section

        if bits is not None:
            return (
                f"This is an MLX {bits}-bit checkpoint. Model-specific quantization predicates "
                "may keep unsupported layers unquantized or at a different precision. "
                f"See the [MLX-Gen quantization docs]({ModelCardSaver.QUANTIZATION_DOC_URL}) "
                "for compatibility notes."
            )

        return "This checkpoint stores MLX-Gen weights without an explicit quantization level."

    @staticmethod
    def _source_model_line(model_name: str) -> str:
        if ModelCardSaver._is_huggingface_repo_id(model_name):
            return f"Original model: [`{model_name}`](https://huggingface.co/{model_name})."
        return f"Original model reference: `{model_name}`."

    @staticmethod
    def _usage_lines(pipeline_tag: str, terms: str) -> list[str]:
        if pipeline_tag == "image-to-image":
            return [
                "  --image path_to_image.png \\",
                '  --prompt "Your edit prompt here" \\',
                "  --steps 20 \\",
                "  --seed 42 \\",
                "  --output edited.png",
            ]

        if "z-image-turbo" in terms or "zimage-turbo" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --steps 8 \\",
                "  --guidance 0 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        if "ernie-image-turbo" in terms or "ernie" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --width 512 \\",
                "  --height 512 \\",
                "  --steps 8 \\",
                "  --guidance 1 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        if "z-image" in terms or "zimage" in terms:
            return [
                '  --prompt "Your prompt here" \\',
                "  --steps 50 \\",
                "  --guidance 4 \\",
                "  --seed 42 \\",
                "  --output image.png",
            ]

        return [
            '  --prompt "Your prompt here" \\',
            "  --steps 20 \\",
            "  --seed 42 \\",
            "  --output image.png",
        ]

    @staticmethod
    def _tags(terms: str, bits: int | None, pipeline_tag: str) -> list[str]:
        tags = ["mlx", "mlx-gen", "mflux", "apple-silicon"]
        if bits is not None:
            tags.append(f"{bits}-bit")
        if bits == 4 and "qwen" in terms:
            tags.extend(["mixed-q4", "mixed-q4-q8"])
        if "qwen" in terms:
            tags.extend(["qwen", "qwen-image"])
        if "edit" in terms or pipeline_tag == "image-to-image":
            tags.append("image-editing")
        if "flux" in terms:
            tags.append("flux")
        if "flux2" in terms or "flux.2" in terms:
            tags.append("flux2")
        if "z-image" in terms or "zimage" in terms:
            tags.append("z-image")
        if "ernie" in terms:
            tags.extend(["ernie", "ernie-image", "ernie-image-turbo"])
        if "fibo" in terms:
            tags.append("fibo")
        return ModelCardSaver._deduplicate(tags)

    @staticmethod
    def _pipeline_tag(terms: str) -> str:
        if any(term in terms for term in ("edit", "kontext", "fill", "depth", "controlnet", "redux")):
            return "image-to-image"
        return "text-to-image"

    @staticmethod
    def _model_terms(model: Any) -> str:
        model_config = getattr(model, "model_config", None)
        values = [
            getattr(model_config, "model_name", ""),
            getattr(model_config, "base_model", ""),
            model.__class__.__name__,
        ]
        values.extend(getattr(model_config, "aliases", []) or [])
        return " ".join(str(value) for value in values if value).lower()

    @staticmethod
    def _contributor_line(bits: int | None) -> str:
        action = "Prepared" if bits is None else "Quantized"
        return f"{action} and contributed by {ModelCardSaver.CONTRIBUTOR}."

    @staticmethod
    def _model_name(model: Any) -> str:
        model_config = getattr(model, "model_config", None)
        return str(getattr(model_config, "model_name", "unknown-model"))

    @staticmethod
    def _repo_name(model_name: str) -> str:
        return Path(model_name).name.lower().replace("_", "-")

    @staticmethod
    def _is_huggingface_repo_id(model_name: str) -> bool:
        return "/" in model_name and model_name.count("/") == 1 and not model_name.startswith(("./", "../", "~/"))

    @staticmethod
    def _is_flux2_9b(model_name: str, terms: str) -> bool:
        normalized = f"{model_name} {terms}".lower()
        return "flux.2-klein" in normalized and "9b" in normalized

    @staticmethod
    def _flux_noncommercial_license_link(model_name: str) -> str:
        if ModelCardSaver._is_huggingface_repo_id(model_name):
            return f"https://huggingface.co/{model_name}/blob/main/LICENSE.md"
        return ModelCardSaver.FLUX_NON_COMMERCIAL_LICENSE_LINK

    @staticmethod
    def _is_apache_model(model_name: str, terms: str) -> bool:
        normalized = f"{model_name} {terms}".lower()
        return (
            "qwen" in normalized
            or "z-image" in normalized
            or "zimage" in normalized
            or "ernie" in normalized
            or ("flux.2-klein" in normalized and "4b" in normalized)
        )

    @staticmethod
    def _deduplicate(values: list[str]) -> list[str]:
        seen = set()
        result = []
        for value in values:
            if value in seen:
                continue
            seen.add(value)
            result.append(value)
        return result
